Cotizacion_Seguros.Web/Models/Cliente/ConsultarCliente.cs
using System.ComponentModel.DataAnnotations;

namespace Cotizacion_Seguros.Web.Models.Cliente
{
    public class ConsultarCliente : RegistrarCliente
    {
        [Display(Name = "Estado civil")]
        public string DescripcionEstadoCivil { get; set; }
    }
}

Cotizacion_Seguros.Web/Models/Cliente/ListarCliente.cs
using System.Collections.Generic;

namespace Cotizacion_Seguros.Web.Models.Cliente
{
    public class ListarCliente
    {
        public ICollection<ConsultarCliente> Clientes { get; set; }
    }
}

Cotizacion_Seguros.Web/Models/Cliente/RegistrarCliente.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using static Cotizacion_Seguros.Application.Utilidades.Enumeraciones;

namespace Cotizacion_Seguros.Web.Models.Cliente
{
    public class RegistrarCliente
    {
        [HiddenInput(DisplayValue = false)]
        public Guid ClienteId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar un número de identificación para el cliente.")]
        [Display(Name = "Número de indentificación *")]
        public string Identificacion { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar el nombre completo del cliente.")]
        [Display(Name = "Nombre completo *")]
        public string Nombre { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar la dirección del cliente.")]
        [Display(Name = "Dirección *")]
        public string Direccion { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar un número de contacto para el cliente.")]
        [Display(Name = "Telefono de contacto *")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "Debe ingresar la fecha de nacimiento del cliente.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de nacimiento *")]
        public DateTime? FechaDeNacimiento { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar el estado civul del cliente.")]
        [Display(Name = "Estado civil *")]
        public int EstadoCivilId { get; set; }
    }
}

Cotizacion_Seguros.Web/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Cotizacion_Seguros.Application.Entidades.Persistencia;
using Cotizacion_Seguros.Application.Interfaces.Servicios;
using Cotizacion_Seguros.Application.Utilidades;
using Cotizacion_Seguros.Web.Models.Cliente;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static Cotizacion_Seguros.Application.Utilidades.Enumeraciones;

namespace Cotizacion_Seguros.Web.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteServicio _ClienteServicio;

        private readonly IMapper _Mapper;

        public ClienteController(IClienteServicio clienteServicio, IMapper mapper)
        {
            _ClienteServicio = clienteServicio;
            _Mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Listar()
        {
            try
            {
                var clientesConsultados = new ListarCliente
                {
                    Clientes = ObtenerDescripcionEstadoCivilParaClientes(_Mapper.Map<IReadOnlyList<ConsultarCliente>>(await _ClienteServicio.ObtenerClientes())).ToList()
                };
                return View(clientesConsultados);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        [HttpGet]
        public IActionResult Registrar()
        {
            ViewBag.EstadoCivil = new SelectList(Negocio.ObtenerEstadosCivilesActivos(), "Value", "Text");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registrar(RegistrarCliente registrarCliente)
        {
            try
            {
                if (!ModelState.IsValid && !Enum.IsDefined(typeof(EstadoCivil), registrarCliente.EstadoCivilId))
                {
                    ViewBag.EstadoCivil = new SelectList(Negocio.ObtenerEstadosCivilesActivos(), "Value", "Text");
                    return View(registrarCliente);
                }

                registrarCliente.ClienteId = Guid.NewGuid();
                await _ClienteServicio.AgregarClienteAsync(_Mapper.Map<Clientes>(registrarCliente));
                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(registrarCliente);
            }

        }

        private IEnumerable<ConsultarCliente> ObtenerDescripcionEstadoCivilParaClientes(IEnumerable<ConsultarCliente> clientes)
        {
            clientes.ToList().ForEach(c => c.DescripcionEstadoCivil = Enum.GetName(typeof(EstadoCivil), c.EstadoCivilId));
            return clientes;
        }
    }
}

Cotizacion_Seguros.Web/Controllers/PolizaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Cotizacion_Seguros.Application.Entidades.Persistencia;
using Cotizacion_Seguros.Application.Interfaces.Servicios;
using Cotizacion_Seguros.Application.Utilidades;
using Cotizacion_Seguros.Web.Models.Seguro;
using Microsoft.AspNetCore.Mvc;
using static Cotizacion_Seguros.Application.Utilidades.Enumeraciones;

namespace Cotizacion_Seguros.Web.Controllers
{
    public class PolizaController : Controller
    {
        private readonly ISeguroServicio _SeguroServicio;

        private readonly IVehiculoServicio _VehiculoServicio;

        private readonly IClienteServicio _ClienteServicio;

        private readonly IMapper _Mapper;

        public PolizaController(ISeguroServicio seguroServicio, IVehiculoServicio vehiculoServicio, IClienteServicio clienteServicio, IMapper mapper)
        {
            _SeguroServicio = seguroServicio;
            _VehiculoServicio = vehiculoServicio;
            _ClienteServicio = clienteServicio;
            _Mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> RegistrarPoliza(Guid clienteId)
        {
            ViewBag.Asesores = Negocio.ObtenerAsesoresActivos(await _SeguroServicio.ObtenerAsesores());
            ViewBag.Polizas = Negocio.ObtenerPolizas();
            return View(new RegistrarSeguro { FkClienteId = clienteId });
        }

        [HttpPost]
        public async Task<IActionResult> RegistrarPoliza(RegistrarSeguro seguroARegistrar)
        {
            try
            {
                if (seguroARegistrar.FkClienteId == Guid.Empty || seguroARegistrar.FkAsesorAsociadoId == Guid.Empty || !Enum.IsDefined(typeof(Polizas), seguroARegistrar.PolizaAsociadaId))
                {
                    ViewBag.Asesores = Negocio.ObtenerAsesoresActivos(await _SeguroServicio.ObtenerAsesores());
                    ViewBag.Polizas = Negocio.ObtenerPolizas();
                    return View(seguroARegistrar);
                }

                var clienteAsociado = await _ClienteServicio.ObtenerClientePorId(seguroARegistrar.FkClienteId);
                var vehiculoARegistrar = _Mapper.Map<Vehiculos>(seguroARegistrar.Vehiculo);
                vehiculoARegistrar.FkClienteId = seguroARegistrar.FkClienteId;
                var vehiculoRegistrado = await _VehiculoServicio.AgregarVehiculoAsync(vehiculoARegistrar);
                var seguroPorRegistrar = _Mapper.Map<Seguros>(seguroARegistrar);
                seguroPorRegistrar.FkVehiculoId = vehiculoRegistrado.VehiculoId;

                if (seguroARegistrar.PolizaAsociadaId == Polizas.SOAT.GetHashCode())
                {
                    seguroARegistrar.CalcularMontoAPagarSoat();
                }
                else
                {
                    seguroARegistrar.CalcularMontoAPagarTodoRiesgo(clienteAsociado.FechaDeNacimiento, clienteAsociado.EstadoCivilId);
                }

                var seguroRegistrado = await _SeguroServicio.AgregarSeguroAsync(seguroPorRegistrar);

                if (seguroARegistrar.PolizaAsociadaId == Polizas.TODORIESGO.GetHashCode())
                {
                    var valoresAGuardar = _Mapper.Map<ValoresAsegurados>(seguroARegistrar.ValoresAPagar);
                    valoresAGuardar.FkSeguroId = seguroRegistrado.SeguroId;
                    var valoresGuardados = await _SeguroServicio.AgregarValoresAseguradosAsync(valoresAGuardar);
                }

                return RedirectToAction("Listar", "Cliente");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(seguroARegistrar);
            }
        }
    }
}

Cotizacion_Seguros.Web/Controllers/VehiculoController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Cotizacion_Seguros.Application.Interfaces.Servicios;
using Cotizacion_Seguros.Web.Models.Vehiculo;
using Microsoft.AspNetCore.Mvc;
using static Cotizacion_Seguros.Application.Utilidades.Enumeraciones;

namespace Cotizacion_Seguros.Web.Controllers
{
    public class VehiculoController : Controller
    {
        private readonly IVehiculoServicio _VehiculoServicio;

        private readonly IMapper _Mapper;

        private readonly ISeguroServicio _SeguroServicio;

        private readonly IClienteServicio _ClienteServicio;

        public VehiculoController(IVehiculoServicio vehiculoServicio, IMapper mapper, ISeguroServicio seguroServicio, IClienteServicio clienteServicio)
        {
            _Mapper = mapper;
            _VehiculoServicio = vehiculoServicio;
            _SeguroServicio = seguroServicio;
            _ClienteServicio = clienteServicio;
        }

        [HttpGet]
        public async Task<IActionResult> Listar(Guid guClienteId)
        {
            try
            {
                if (guClienteId != Guid.Empty)
                {
                    var vehiculos = await _VehiculoServicio.ListarVehiculosPorClienteAsync(guClienteId);
                    var clienteAsociado = await _ClienteServicio.ObtenerClientePorId(guClienteId);

                    if (vehiculos.Any())
                    {
                        var seguros = await _SeguroServicio.ObtenerSegurosPorVehiculosIdAsync(vehiculos.Select(v => v.VehiculoId).ToList());
                        return View(new ListarVehiculo()
                        {
                            Vehiculos = seguros.Select(s => new ConsultarVehiculo
                            {
                                Anio = s.VehiculoAsociado.Anio,
                                Modelo = s.VehiculoAsociado.Modelo,
                                MontoPagado = s.MontoAPagar,
                                Placa = s.VehiculoAsociado.Placa,
                                ValorComercial = s.VehiculoAsociado.ValorComercial,
                                SerialDeCarroceria = s.VehiculoAsociado.SerialDeCarroceria,
                                DescripcionPoliza = Enum.GetName(typeof(Polizas), s.PolizaAsociadaId)
                            }).ToList(),
                            NombreDelCliente = clienteAsociado.Nombre
                        });
                    }

                    return View(new ListarVehiculo() { NombreDelCliente = clienteAsociado.Nombre });
                }

                return View(new ListarVehiculo() { NombreDelCliente = "No existe el cliente indicado." });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Cotizacion_Seguros.Web/Views/Cliente/Listar.cshtml
@model Cotizacion_Seguros.Web.Models.Cliente.ListarCliente

@{
    ViewData["Title"] = "Listado de clientes";
}

<div class="container">
    <div class="row">
        <div class="col-md-7">
            <h4>Listado de clientes</h4>
        </div>
        <div class="col-md-5 text-right">
            <a asp-action="Index" asp-controller="Home" class="btn btn-outline-info">Volver</a>
            <a asp-action="Registrar" class="btn btn-outline-primary">Registrar cliente</a>
        </div>
    </div>
</div>

<table class="table">
    <thead class="text-center">
        <tr>
            <th>
                Identificación
            </th>
            <th>
                Nombre
            </th>
            <th>
                Direccion
            </th>
            <th>
                Telefono
            </th>
            <th>
                Fecha de nacimiento
            </th>
            <th>
                Estado civil
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Clientes != null && Model.Clientes.Any())
        {
            foreach (var item in Model.Clientes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Identificacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Direccion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaDeNacimiento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DescripcionEstadoCivil)
                    </td>
                    <td class="text-center">
                        <div class="dropdown">
                            <button class="btn btn-default btn-sm" type="button" id="menuContratos" data-toggle="dropdown"><strong class="text-black-50">...</strong></button>
                            <div class="dropdown-menu" aria-labelledby="menuContratos" style="cursor:pointer">
                                <a class="dropdown-item" href="@Url.Action("Listar", "Vehiculo", new { guClienteId = item.ClienteId })"><span class="fa fa-automobile"></span> &nbsp; Ver vehículos</a>
                                <a class="dropdown-item" href="@Url.Action("RegistrarPoliza", "Poliza", new { clienteId = item.ClienteId })"><span class="fa fa-edit"></span> &nbsp; Registrar vehículo</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Cotizacion_Seguros.Web/Views/Cliente/Registrar.cshtml
@model Cotizacion_Seguros.Web.Models.Cliente.RegistrarCliente

@{
    ViewData["Title"] = "Registrar Cliente";
}

<h4>Diligencie los campos para registrar un cliente</h4>
<hr />
<div class="container">
    <form asp-action="Registrar">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="Identificacion" class="control-label"></label>
                <input asp-for="Identificacion" class="form-control" />
                <span asp-validation-for="Identificacion" class="text-danger"></span>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="EstadoCivilId" class="control-label"></label>
                <select asp-for="EstadoCivilId" asp-items="ViewBag.EstadoCivil" class="form-control"></select>
                <span asp-validation-for="EstadoCivilId" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="FechaDeNacimiento" class="control-label"></label>
                <input asp-for="FechaDeNacimiento" class="form-control" />
                <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
            </div>
        </div>
        <hr />
        <div class="row text-right">
            <div class="col-md-12">
                <a asp-action="Listar" asp-controller="Cliente" class="btn btn-info">Cancelar</a>
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}